// Portfolio data organized by service category. All assets are local files from disk D workspace.
const portfolioData = {
  graphics: [
    { id: 'graphics-1', title: 'Vote Aggy Political Campaign', category: 'graphics', subcategory: 'Poster Design', image: 'vote AGGY.png', date: '2024', description: 'High-impact political campaign poster with strong hierarchy and fast audience recognition.', clientIndustry: 'Politics', tools: 'Photoshop, Illustrator', timeline: '2 days', outcome: 'Campaign-ready print and social artwork', testimonial: 'The design attracted attention immediately.', featured: true },
    { id: 'graphics-2', title: 'Premium Business Cards', category: 'graphics', subcategory: 'Business Cards', image: 'BUSINESS CARD 2.png', date: '2024', description: 'Elegant business card layout with polished corporate presentation.', clientIndustry: 'Corporate', tools: 'Illustrator', timeline: '1 day', outcome: 'Print-ready identity collateral', testimonial: 'Clean, sharp and professional.' },
    { id: 'graphics-3', title: 'Event Poster Campaign', category: 'graphics', subcategory: 'Posters', image: 'FRANCO POSTER.png', date: '2024', description: 'Bold event poster created for quick recognition across online and print channels.', clientIndustry: 'Events', tools: 'Photoshop', timeline: '1 day', outcome: 'Improved campaign visibility', testimonial: 'The poster stood out online.' }
  ],
  video: [
    { id: 'video-20260123-0004', title: 'Client Video Edit 0004', category: 'video', subcategory: 'Video Editing', type: 'video', video: 'VID-20260123-WA0004.mp4', image: 'assets/generated/video-posters/vid-20260123-wa0004-poster.svg', poster: 'assets/generated/video-posters/vid-20260123-wa0004-poster.svg', date: '2026', description: 'Uploaded client video integrated into the media services gallery with local playback and preview support.', clientIndustry: 'Media Services', tools: 'Video editing workflow', timeline: 'Uploaded media', outcome: 'Hosting-ready video preview', testimonial: 'Real uploaded project media.', featured: true },
    { id: 'video-20260123-0006', title: 'Client Video Edit 0006', category: 'video', subcategory: 'Media Services', type: 'video', video: 'VID-20260123-WA0006.mp4', image: 'assets/generated/video-posters/vid-20260123-wa0006-poster.svg', poster: 'assets/generated/video-posters/vid-20260123-wa0006-poster.svg', date: '2026', description: 'Real uploaded media file added to replace placeholder demo video content.', clientIndustry: 'Media Services', tools: 'Video editing workflow', timeline: 'Uploaded media', outcome: 'Responsive video card and modal playback', testimonial: 'Ready for portfolio viewing.' },
    { id: 'video-20260125-0001', title: 'Short-Form Video Edit 0001', category: 'video', subcategory: 'Reels and Shorts', type: 'video', video: 'VID-20260125-WA0001.mp4', image: 'assets/generated/video-posters/vid-20260125-wa0001-poster.svg', poster: 'assets/generated/video-posters/vid-20260125-wa0001-poster.svg', date: '2026', description: 'Uploaded short-form video prepared for desktop and mobile gallery playback.', clientIndustry: 'Social Media', tools: 'CapCut, Premiere-style editing', timeline: 'Uploaded media', outcome: 'Mobile-friendly video preview', testimonial: 'Real media sample added.', featured: true },
    { id: 'video-20260125-0003', title: 'Edited Video Project 0003', category: 'video', subcategory: 'Video Production', type: 'video', video: 'VID-20260125-WA0003.mp4', image: 'assets/generated/video-posters/vid-20260125-wa0003-poster.svg', poster: 'assets/generated/video-posters/vid-20260125-wa0003-poster.svg', date: '2026', description: 'Uploaded video project displayed with local poster preview, controls, and modal viewing.', clientIndustry: 'Client Project', tools: 'Video editing workflow', timeline: 'Uploaded media', outcome: 'Portfolio-ready media card', testimonial: 'Real project video included.' },
    { id: 'video-20260311-0006', title: 'Client Media Edit 0006', category: 'video', subcategory: 'Client Media', type: 'video', video: 'VID-20260311-WA0006.mp4', image: 'assets/generated/video-posters/vid-20260311-wa0006-poster.svg', poster: 'assets/generated/video-posters/vid-20260311-wa0006-poster.svg', date: '2026', description: 'Recent uploaded video added to the media services section with lazy loading behavior.', clientIndustry: 'Client Project', tools: 'Video editing workflow', timeline: 'Uploaded media', outcome: 'Playable media preview', testimonial: 'Latest media sample added.' },
    { id: 'video-20260311-0007', title: 'Promotional Media Edit 0007', category: 'video', subcategory: 'Promo Videos', type: 'video', video: 'VID-20260311-WA0007.mp4', image: 'assets/generated/video-posters/vid-20260311-wa0007-poster.svg', poster: 'assets/generated/video-posters/vid-20260311-wa0007-poster.svg', date: '2026', description: 'Uploaded promotional video integrated for preview cards and modal playback.', clientIndustry: 'Promotion', tools: 'Video editing workflow', timeline: 'Uploaded media', outcome: 'Responsive video presentation', testimonial: 'Real uploaded promo media.' },
    { id: 'video-20260311-0008', title: 'Social Video Edit 0008', category: 'video', subcategory: 'Social Video', type: 'video', video: 'VID-20260311-WA0008.mp4', image: 'assets/generated/video-posters/vid-20260311-wa0008-poster.svg', poster: 'assets/generated/video-posters/vid-20260311-wa0008-poster.svg', date: '2026', description: 'Uploaded social video added to recent work, portfolio, and service galleries.', clientIndustry: 'Social Media', tools: 'Video editing workflow', timeline: 'Uploaded media', outcome: 'Hosting-ready local video playback', testimonial: 'Real social media video sample.' }
  ],
  websites: [
    { id: 'web-1', title: 'Modern Business Website', category: 'websites', subcategory: 'Business Website', image: 'WEBSITE DESIGN.png', date: '2024', description: 'Responsive business website structure with service-led conversion flow.', clientIndustry: 'Technology', tools: 'HTML, CSS, JavaScript', timeline: '7 days', outcome: 'Professional online presence', testimonial: 'The site made the brand look established.', featured: true },
    { id: 'web-2', title: 'E-commerce Website Plan', category: 'websites', subcategory: 'E-commerce', image: 'WEBSITE DESIGN.png', date: '2024', description: 'Shop-ready website concept with product categories and quote pathways.', clientIndustry: 'Retail', tools: 'WordPress, WooCommerce, UI/UX', timeline: '10 days', outcome: 'Clear buying journey', testimonial: 'Customers understood the products faster.' }
  ],
  branding: [
    { id: 'brand-1', title: 'Tenecious Brand Identity', category: 'branding', subcategory: 'Logo & Brand Kit', image: 'TENECIOUS LOGO.png', date: '2024', description: 'Logo presentation and visual system for consistent brand recognition.', clientIndustry: 'Consumer Brand', tools: 'Illustrator, Photoshop', timeline: '5 days', outcome: 'Complete brand kit direction', testimonial: 'The identity finally looked consistent.', featured: true },
    { id: 'brand-2', title: 'Logo Design Presentation', category: 'branding', subcategory: 'Logo Design', image: 'LOGO DESIGN.jpeg', date: '2024', description: 'Professional logo concept with clean mockup presentation.', clientIndustry: 'Corporate', tools: 'Illustrator', timeline: '3 days', outcome: 'Ready-to-use logo assets', testimonial: 'Exactly the premium look we needed.', featured: true }
  ],
  printing: [
    { id: 'print-1', title: 'Large Format Banner', category: 'printing', subcategory: 'Banners', image: 'BANNER 1.JPG', date: '2024', description: 'Outdoor banner artwork prepared for high-visibility print production.', clientIndustry: 'Advertising', tools: 'Photoshop, Print setup', timeline: '2 days', outcome: 'Large format print-ready design', testimonial: 'The banner was clear from far away.', featured: true },
    { id: 'print-2', title: 'T-Shirt Merchandise', category: 'printing', subcategory: 'Merchandise', image: 'TSHIRT MOCKUP.png', date: '2024', description: 'Branded shirt mockups and print preparation for merchandise.', clientIndustry: 'Apparel', tools: 'Photoshop, Mockups', timeline: '2 days', outcome: 'Merchandise-ready artwork', testimonial: 'The mockups helped us approve fast.', featured: true },
    { id: 'print-3', title: 'Cups and Bottles Branding', category: 'printing', subcategory: 'Merchandise', image: 'CUPSANDBOTTLE.png', date: '2024', description: 'Product branding for promotional cups and bottles.', clientIndustry: 'Retail', tools: 'Photoshop', timeline: '2 days', outcome: 'Branded promotional products', testimonial: 'The products looked professional.' }
  ],
  it: [
    { id: 'it-1', title: 'Workstation Setup', category: 'it', subcategory: 'Hardware Installation', image: 'HON. KEN (1).png', date: '2024', description: 'Device setup, software installation and workflow configuration for reliable daily use.', clientIndustry: 'Small Business', tools: 'Windows, Drivers, Networking', timeline: '1 day', outcome: 'Stable workstation setup', testimonial: 'The system became faster and easier to use.', featured: true },
    { id: 'it-2', title: 'System Troubleshooting', category: 'it', subcategory: 'IT Support', image: 'BeautyPlus_20240428221327568_save_1-removebg-preview.png', date: '2024', description: 'Diagnostics and technical support for device performance issues.', clientIndustry: 'Individual Client', tools: 'Diagnostics, Software setup', timeline: 'Same day', outcome: 'Resolved performance problems', testimonial: 'Quick and professional support.' },
    { id: 'it-installation-1', title: 'Digital Infrastructure Installation', category: 'it', subcategory: 'Installation', image: 'INSTALLATION.jpg', date: '2026', description: 'Uploaded installation media mapped into IT consultation and hardware infrastructure services.', clientIndustry: 'Institution', tools: 'Networking, setup, installation', timeline: 'Project based', outcome: 'Reliable technical setup', testimonial: 'Installation media added from real project files.', featured: true },
    { id: 'it-cctv-1', title: 'CCTV and Security Setup', category: 'it', subcategory: 'CCTV Installation', image: 'CCTV.jpg', date: '2026', description: 'Security and CCTV installation sample added from uploaded project assets.', clientIndustry: 'Business and institutions', tools: 'CCTV, cabling, access control', timeline: 'Project based', outcome: 'Improved site security', testimonial: 'Real security installation sample.' },
    { id: 'it-support-1', title: 'IT Support Service Session', category: 'it', subcategory: 'Technical Support', image: 'IT ONE.jpg', date: '2026', description: 'IT support media added to show hands-on consultation and technical service delivery.', clientIndustry: 'Business and individual clients', tools: 'Diagnostics, setup, support', timeline: 'Same day or scheduled', outcome: 'Improved system reliability', testimonial: 'Real IT service media added.' },
    { id: 'it-school-1', title: 'School ICT Support Sample', category: 'it', subcategory: 'School IT', image: 'SCHOOL.jpg', date: '2026', description: 'School technology media mapped to IT support services for institutions and learning environments.', clientIndustry: 'Schools', tools: 'ICT support, networking, digital learning', timeline: 'Project based', outcome: 'Better school technology readiness', testimonial: 'School media sample added.' }
  ],
  repairs: [
    { id: 'repair-1', title: 'Laptop Repair and Upgrade', category: 'repairs', subcategory: 'Hardware Repair', image: 'HON. KEN (1).png', date: '2024', description: 'Laptop diagnosis, part replacement planning and performance upgrade support.', clientIndustry: 'Consumer', tools: 'Hardware diagnostics, SSD/RAM setup', timeline: '1-2 days', outcome: 'Improved device speed and reliability', testimonial: 'My laptop works much better now.', featured: true },
    { id: 'repair-2', title: 'Desktop Workstation Repair', category: 'repairs', subcategory: 'Desktop Repair', image: 'WEBSITE DESIGN.png', date: '2024', description: 'Desktop repair support and replacement component sourcing.', clientIndustry: 'Small Business', tools: 'Hardware testing, OS setup', timeline: '1 day', outcome: 'Operational workstation restored', testimonial: 'Professional repair and clear advice.' },
    { id: 'repair-upload-1', title: 'Repair Service Project', category: 'repairs', subcategory: 'Repair Service', image: 'REPAIR.jpg', date: '2026', description: 'Uploaded repair media added to the hardware repair gallery without replacing existing samples.', clientIndustry: 'Hardware Support', tools: 'Diagnostics, repair, maintenance', timeline: 'Service based', outcome: 'Device service documentation', testimonial: 'Real repair project asset added.', featured: true },
    { id: 'repair-installation-1', title: 'Hardware Installation Support', category: 'repairs', subcategory: 'Installation', image: 'INSTALLATION.jpg', date: '2026', description: 'Installation file automatically classified into repair and hardware support because the filename contains installation.', clientIndustry: 'Business and institutions', tools: 'Installation, configuration, testing', timeline: 'Project based', outcome: 'Hardware and systems installed', testimonial: 'Uploaded installation media included.' },
    { id: 'repair-service-1', title: 'On-Site IT Service', category: 'repairs', subcategory: 'Service Support', image: 'IT ONE.jpg', date: '2026', description: 'Service-focused IT media added to support repair and hardware consultation galleries.', clientIndustry: 'Client support', tools: 'Diagnostics, technical support', timeline: 'Scheduled service', outcome: 'Reliable system support', testimonial: 'Real service media sample.' },
    { id: 'repair-cctv-1', title: 'Security Hardware Installation', category: 'repairs', subcategory: 'Hardware Installation', image: 'CCTV.jpg', date: '2026', description: 'CCTV hardware installation media added alongside existing repair placeholders.', clientIndustry: 'Security systems', tools: 'CCTV, cabling, hardware setup', timeline: 'Project based', outcome: 'Security hardware installed', testimonial: 'Uploaded CCTV media included.' }
  ]
};
function getProjectsByCategory(category) { return portfolioData[category] || []; }
function getAllProjects() { return Object.values(portfolioData).flat(); }
function getFeaturedProjects() { return getAllProjects().filter((project) => project.featured); }
